### PR TITLE
Create initial post for call for contrib

### PR DESCRIPTION
**Pull request by postphotos**
Writing post for contrib help for http://averyserious.website
<3

8-)

### CODE REVIEW

**Comment by postphotos** [comment]
@julioberina

**Review by julioberina — COMMENTED** [review]
lgtm

**Review by julioberina — APPROVED** [review]

**Review by davidnuon — DISMISSED** [review]
Change "the Dutch's" to "the Netherlands' " we get

**Comment by postphotos** [comment]
Thanks folks! 👍

**Pull request merged**
